receivers:
  otlp:
    protocols:
      http:

processors:
  batch:

exporters:
  logging:
    # basic | normal | detailed
    verbosity: detailed
  otlp/jaeger:
    endpoint: "http://jaeger:4317"
    tls:
      insecure: true
service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp/jaeger]
    logs:
      receivers: [otlp]
      exporters: [logging]